site:
  title: "Daniel Oltmanns"
  subtitle: "personal blog and collection of tips"
  description: |
    A personal blog sharing hands-on tips in programming, PCB design, and cybersecurity—exploring tech from code to hardware.
  url: https://oltdaniel.eu
  email: hi@oltdaniel.eu
  socials:
  - name: GitHub
    url: https://github.com/oltdaniel
  - name: Codeberg
    url: https://codeberg.org/oltdaniel

navigation:
  - title: "Home"
    url: "/"
  - title: "Tips"
    url: "/tips/"
  - title: "Blog"
    url: "/blog/"

collections:
  blog:
    path: "content/blog"
    type: "markdown"
    template: "post.html"
    index_template: "blog/index.html"
    output_dir: "blog"
    permalink: "/blog/:year/:slug:output_ext"
  tips:
    path: "content/tips"
    type: "markdown"
    template: "post.html"
    index_template: "tips/index.html"
    output_dir: "tips"
    permalink: "/tips/:year/:slug:output_ext"
  pages:
    path: "content/pages"
    type: "mixed"
    template: "page.html"
    output_dir: ""
    allow_subdirectory: true
