name: github pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Action - rsync
        uses: up9cloud/action-rsync@v1.3
        env:
            HOST: oltdaniel.eu
            USER: ${{secrets.DEPLOY_USER}}
            KEY: ${{secrets.DEPLOY_SSH_KEY}}
            TARGET: ${{secrets.DEPLOY_TARGET}}
            SOURCE: ./public/
            ARGS_MORE: --no-o --no-g --no-perms -O -J